# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 475373c0e89f82756fb8c980844663775ee46f6b77250218b95b6ed9e19564b44861e1f7e91b7480a0f64ddf4812b90d84e76fa6c4f33e258b8b637ad71b134f

test:
  secret_key_base: 8028f423091e84ed4d3482989c20a3a5cafc297242eeccb57045eaa84ba8f0fc3301fd5acaa1a3eb0df123f78fa907e6ce1fc35589e9a30b6eef90a99510f57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
